Repository lukaskabrt/PoExtractor, pull requests merged in 2020-10, with the labels that each got.

#38 Support Pages folder for Razor Pages
  PoExtractor.Core.Tests/LocalizableStringCollectionTests.cs
  PoExtractor.Razor/ViewCompiler.cs
  azure-pipelines.yml
  global.json
Labels: size/S

#41 Add support for razor components
  PoExtractor.Razor/ViewCompiler.cs
Labels: size/S

#35 Update readme with preview version note
  readme.md
Labels: size/XS

#40 Extract strings from DisplayAttribute
  PoExtractor.Core.Tests/DisplayAttributeStringExtractorTests.cs
  PoExtractor.Core.Tests/ErrorMessageAnnotationStringExtractorTests.cs
  PoExtractor.Core.Tests/Fakes/FakeCSharpProjectProcessor.cs
  PoExtractor.Core.Tests/ProjectFiles/PersonModel.cs
  PoExtractor.DotNet.CS/CSharpProjectProcessor.cs
  PoExtractor.DotNet.VB/VisualBasicProjectProcessor.cs
  PoExtractor.DotNet/DisplayAttributeDescriptionStringExtractor.cs
  PoExtractor.DotNet/DisplayAttributeGroupNameStringExtractor.cs
  PoExtractor.DotNet/DisplayAttributeNameStringExtractor.cs
  PoExtractor.DotNet/DisplayAttributeShortNameStringExtractor.cs
  PoExtractor.DotNet/DisplayAttributeStringExtractor.cs
  PoExtractor.DotNet/ErrorMessageAnnotationStringExtractor.cs
Labels: size/L
